#!/bin/sh

if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
  echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
  ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
fi

exec /usr/sbin/sshd -D -f /etc/ssh/sshd_config
